name: exper_global
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  rxdart: ^0.27.0
  dio: ^4.0.0
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1
  full_text_search: ^0.8.0+2

  flutter:
    sdk: flutter
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  firebase_storage: ^8.0.5
  cloud_firestore: ^2.0.0
  provider: ^5.0.0
  animated_size_and_fade: ^2.0.0
  image_picker: ^0.7.4
  country_currency_pickers: ^2.0.0
  timelines: ^0.1.0
  flutter_svg: ^0.22.0
  flutter_colorpicker: ^0.4.0
  flutter_tags: ^1.0.0-nullsafety.1
  cached_network_image: ^3.0.0
  sticky_headers: ^0.2.0
  video_player: ^2.1.5
  lottie: ^1.0.1

dev_dependencies:
  build_runner: ^2.0.1
  freezed: ^0.14.1+3
  json_serializable: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo-icon.svg
    - assets/logo.svg
    - assets/logo-full.svg
    - assets/pages/home/
    - assets/pages/home/freight/
    - assets/pages/home/features/
    - assets/pages/home/social-media/
    - assets/pages/home/applications/
    - assets/pages/home/applications/stores/
    - assets/pages/about/
    - assets/pages/services/
    - assets/pages/locations/
    - assets/pages/partners/
